# Generated by Django 5.0.14 on 2026-06-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the tool', max_length=120)),
                ('slug', models.SlugField(help_text='URL-safe identifier', unique=True)),
                ('category', models.CharField(choices=[('graph', 'Graph & Structural Parsers'), ('math', 'Algorithmic Math & Analytics'), ('syntax', 'Syntax Boilerplate & Macro Builders')], max_length=60)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Atomic visit counter')),
            ],
            options={
                'verbose_name': 'Tool Metadata',
                'verbose_name_plural': 'Tool Metadata',
                'ordering': ['category', 'name'],
            },
        ),
    ]
